language: python
dist: "xenial"
python:
  - "3.6"
  - "3.7"
before_install:
  - python --version
init:
    pip install pipenv
    pipenv install --dev
test:
    pipenv run pytest --cov=edinet tests/
after_success:
  codecov
