language: python
dist: "xenial"
python:
  - "3.6"
  - "3.7"
before_install:
  - python --version
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run pytest --cov=edinet tests/
after_success:
  - codecov
